### PR TITLE
Custom Role and Permission classes

### PR DESCRIPTION
**Pull request by suleymanozev**
Feature Added #33

### CODE REVIEW

**Comment by suleymanozev** [comment]
@bezhanSalleh please review

**Comment by bezhanSalleh** [comment]
@suleymanozev this package uses spatie's `larave-permission` so in order to use a custom `Role` or `Permission` model that package's guideline should be considered as stated here https://spatie.be/docs/laravel-permission/v5/advanced-usage/extending. As for the enforcing the `RolePolicy` just turened of from the setting or config file and register your custom ones manually.

Shield is not fully ready to use custom models on its own so i'm gonna hold of on mergin your PR.
Thanks.

**Comment by suleymanozev** [comment]
I already known this guideline [https://spatie.be/docs/laravel-permission/v5/advanced-usage/extending](https://spatie.be/docs/laravelpermission/v5/advanced-usage/extending). I have already made the changes, I am using it as it is now and there is no problem.

Role class in your code is hard coded. Spatie's library already has a config key.
I want to use this package. It should be a package that appeals to everyone. What I did in this pull request will allow us to use Spatie's features.

Please review again. You will understand what I mean.

**Comment by suleymanozev** [comment]
For Example in line 8: 
https://github.com/bezhanSalleh/filament-shield/blob/f28d254ecb5ab704a5355b8d2be68f6f1942a2f7/src/FilamentShield.php#L1-L9

And usage:
https://github.com/bezhanSalleh/filament-shield/blob/f28d254ecb5ab704a5355b8d2be68f6f1942a2f7/src/FilamentShield.php#L56-L67

In line 59: should **`config('permission.models.role')::firstOrCreate`**

**Comment by suleymanozev** [comment]
@bezhanSalleh

**Pull request closed without merging**
