### PR TITLE
Fix issue on phpstan

### PR DESCRIPTION
**Pull request by lloricode**
```
 ------ ------------------------------------------------------- 
  Line   app/Policies/RolePolicy.php                            
 ------ ------------------------------------------------------- 
  43     PHPDoc tag @param references unknown parameter: $role  
 ------ ------------------------------------------------------- 
```

### CODE REVIEW

**Comment by lloricode** [comment]
also since this is now in php8+, can we add return type for it, and also we can remove all doc block and replace it with actual type hint parameters? since this is much readable than comment doc block

**Comment by lloricode** [comment]
and also the function is descriptive, so no need to explain with short sentence

**Comment by bezhanSalleh** [comment]
it's currently compliant with laravel policy generation, plus the RolePolicy doesnt come outta the box with the plugin so to each his own... so when laravel changes them, then will do the same. but you are free to do it for yourself however you want.

**Comment by lloricode** [comment]
i see, but can you fix the issue with phpstan? i think this is not from laravel stub

**Comment by bezhanSalleh** [comment]
sure next release

**Comment by lloricode** [comment]
that's great, thank you

**Comment by bezhanSalleh** [comment]
@lloricode fixed in 2.2.5

**Pull request closed without merging**
