### PR TITLE
Fix filament 3

### PR DESCRIPTION
**Pull request by makzumi**
Added Panel support for filament 3.
With this update panels get their own tab in the "roles" resource.

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
hey thanks for the PR. but having the panels like this doesn't add any essential value as whole for the package.
Because at the most you might have 5 panels or maybe even 10. and you can handle that through custom permissions. which was kinda built for this sorta thing. though some might find it usefull but the majority of users might even frown upon it. now don't take it the wrong way, but in my mind unless a feature doesn't add or cover the needs of the majority of the users who uses this package based on my experience then that feature shouldn't be in the package.

you can use it yourself though, just publish the resource and add your logic there. and if you have the time make it a gist and post it on shield's discord channel for others who wants it use.

So thanks again. but i'm gonna close it.

**Comment by makzumi** [comment]
No worries, I just found it useful/convenient to be able to control access to panels for roles from the package.
Thanks for taking the time to explain why you closed it.
I tried doing the custom permissions at 1st, but could get it working so I went down this route, any tips on getting panel to work with that?
Thanks again!

**Comment by makzumi** [comment]
Forgot to mention, my PR also made all resources, widgets, pages, etc... available in one panel. So for example you can edit all Roles/Permission and have access to all from, let's say the "Admin" panel.
Currently you only get Resources, Widgets, etc... created for that particular panel, so you need to jump from panel to panel to edit roles/permissions. Can get quite messy if you want a consolidated admin experience.
Dunno if that makes sense.

**Comment by bezhanSalleh** [comment]
in short you started with good intention but you made to unique to fit your own use case. it should have been a setting, like `discoverAllResources()`, `discoverAllPages()`, `discoverAllWidgets()` and there those custom permissions would come in to play... you would have a prefix like other entities in filament as `canAccessPanel` then based on these custom permissions and the setting you would merge or not merge other panel entities and show/hide as well if the user had the permission for the panel.

**Comment by bezhanSalleh** [comment]
in short you started with good intention but you made to unique to fit your own use case. it should have been a setting, like `discoverAllResources()`, `discoverAllPages()`, `discoverAllWidgets()` and there those custom permissions would come in to play... you would have a prefix like other entities in filament as `canAccessPanel` then based on these custom permissions and the setting you would merge or not merge other panel entities and show/hide as well if the user had the permission for the panel.

**Pull request closed without merging**
