### PR TITLE
Discovery

### PR DESCRIPTION
**Pull request by makzumi**
Hi Bezhan,

Followed your lead from my last PR and I added a new feature to show all resources, pages, widgets from different panels in a single panel.
Hope this one makes it,
Thanks
Added new config group to toggle on and off.

### CODE REVIEW

**Review by bezhanSalleh — CHANGES_REQUESTED** [review]
implement the new methods in `Utils` class.

**Comment by aeq-dev** [comment]
Something is cooking here :) can't wait for it

**Comment by makzumi** [comment]
> implement the new methods in `Utils` class.

Hey Bezhan, hmmm, I don't see how I can move this into Utils since I need to change how the resources, etc... are collected. @bezhanSalleh

**Comment by bezhanSalleh** [comment]
> > implement the new methods in `Utils` class.
> 
> Hey Bezhan, hmmm, I don't see how I can move this into Utils since I need to change how the resources, etc... are collected. @bezhanSalleh

first of all, you don't have to @ me caz i will get notified either way.
second, you have a couple of calls for those discover methods from utils but the methods are not implemented in there. so they are missing. if anyone pulls in your PR it doesn't work because of it.

**Comment by makzumi** [comment]
I'm sorry, I see what you're saying. I'll update the PR soon, thanks

**Comment by makzumi** [comment]
PR updated

**Review by bezhanSalleh — APPROVED** [review]

**Comment by bezhanSalleh** [comment]
Thanks!

**Pull request merged**
