### PR TITLE
Feature/performance boost

### PR DESCRIPTION
**Pull request by bezhanSalleh**
closes #200

there is still a bug which in edit mode with bulktoggleable, didn't have time to figure it out. 
don't know if it's my doing or filament/livewire issue.

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
gif

**BUG**

https://github.com/bezhanSalleh/filament-shield/assets/10007504/bab14b3c-eea1-45ee-a55f-8c1987999ffd

**Comment by bezhanSalleh** [comment]
should be merged and released when 
https://github.com/filamentphp/filament/pull/8061 PR is merged and released in filament v3

**Comment by Shipu** [comment]
Your filament v3 PR is merged. you merge this pull request

**Comment by bezhanSalleh** [comment]
> Your filament v3 PR is merged. you merge this pull request

that fixes one issue, but there is bug in the `afterStateUpdated()` lifecycle hook of the `CheckboxList` component, which i didn't have time to figure out. fixed it for v2 but for v3 using a workaround.

will be releaseing it this weekend hopefully! for both shield v2 and v3

closes #204

**Pull request merged**
