### PR TITLE
Allow json translation from project lang for widget name

### PR DESCRIPTION
**Pull request by abdosaeedelhassan**
Allow json translation from project lang for widget name, the modification in FilamentShield class only but phpstorm autoreformat code in other files, if you do not liked i will reverted.

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
Yeah plz revert the formatting, we already have a pint action for it.

**Review by bezhanSalleh — CHANGES_REQUESTED** [review]
revert formatting.

**Comment by abdosaeedelhassan** [comment]
> revert formatting.

Now i did, i think  in you code 
`str($widget)
                ->afterLast('\\')
                ->headline()
                ->toString()`
if changing headline to ucfirst will be good

**Comment by bezhanSalleh** [comment]
> > revert formatting.
> 
> Now i did, i think in you code `str($widget) ->afterLast('\\') ->headline() ->toString()` if changing headline to ucfirst will be good

Now I can clearly see what you are trying to achive. From the looks of it, this PR isn't necessary. Because, you can already achieve what you want to do and the default section of the code is for when you forget to name a widget.
So to format/translate widget names(Heading in Filament):
For `TableWidget` through `heading()` method:
```php
    public function table(Table $table): Table
    {
        return $table
            ->heading(__('yourApp.widgets.latestOrders'))
            ...
     }
```
For `ChartWidget` through `getHeading()` method:
```
    public function getHeading(): string | Htmlable | null
    {
        return __('yourApp.widgets.latestOrders');
    }
```
For custom `Widgets` and `StatsOverviewWidget` just add a `getHeading()` method like `ChartWidget` and you are done.
I hope this makes it clear so i will close the PR and thank you.

**Pull request closed without merging**
