### PR TITLE
feat: use config models

### PR DESCRIPTION
**Pull request by FurkanGM**
When extend role or permission model, we should use the model specified in the config so that we do not get errors in filament dashboard or commands.

Example extend, uuid based role and permission https://spatie.be/docs/laravel-permission/v5/advanced-usage/uuid

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
hey, could you check it out with v2.3.0 and see there is no issue and resolve the custom models from Utils instead of the `FilamentShield` and let me know... thanks

**Comment by FurkanGM** [comment]
Hi, I merged and tested v2.3.0. I didn't have any problems. You can review :)

**Comment by Z3d0X** [comment]
Not sure if this is better, but just stating this is possible ✌️ 

```
use Spatie\Permission\PermissionRegistrar;
app(PermissionRegistrar::class)->getPermissionClass();

use Spatie\Permission\Contracts\Permission;
app(Permission::class);
```

**Comment by bezhanSalleh** [comment]
> Not sure if this is better, but just stating this is possible ✌️
> 
> ```
> use Spatie\Permission\PermissionRegistrar;
> app(PermissionRegistrar::class)->getPermissionClass();
> 
> use Spatie\Permission\Contracts\Permission;
> app(Permission::class);
> ```

yeah i know, the reason i asked @FurkanGM to resolve the models via utils was, we can set `Permission` and `Role` class through the `PermissionRegistrar` as well;
```php
use Spatie\Permission\PermissionRegistrar;

app(PermissionRegistrar::class)
   ->setPermissionClass(MyCustomePermission::class)
   ->setRoleClass(MyCustomRole::class);

```
anyhow, now we can easily turn this:
```php
    public static function getRoleModel(): string
    {
        return config('permission.models.role');
    }

    public static function getPermissionModel(): string
    {
        return config('permission.models.permission');
    }
```
into :
```php
   use Spatie\Permission\PermissionRegistrar;
   
    public static function getRoleModel(): string
    {
        return app(PermissionRegistrar::class)->getRoleClass();
    }

    public static function getPermissionModel(): string
    {
        return app(PermissionRegistrar::class)->getPermissionClass();
    }
```
so now if someone changes the models through config or permission registrar, either way we will be covered.

**Comment by khumam** [comment]
Can anyone explain how to use it? 
or the complete config because I can't see the `permission.models.role` and `permission.models.permission` neither

**Pull request merged**
