### PR TITLE
Allow role resource configurable

### PR DESCRIPTION
**Pull request by a21ns1g4ts**
Sometimes I need to change certain implementations without rewriting the entire plugin code. With this change, I'll be able to do that.
Currently, I need to modify the navigation label, but it's a translation value. To do that, I need to publish all the translation files, but I don't want to maintain this versioning in my own code. If you make this configurable, I can easily extend my own implementation.

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
You can already do what you want by publishing the resource. Otherwise publish the lang files and only keep the languages you need delete the rest. Because it's not just the title and navigation translations there are column and icon translations as well.

**Comment by a21ns1g4ts** [comment]
@bezhanSalleh  Really, it is a simple change to allow flexibility in the code. But the power to decide not to merge this simple line shows your ego.

**Comment by a21ns1g4ts** [comment]
@bezhanSalleh Simply, you could allow us to modify the class implementation.

**Comment by a21ns1g4ts** [comment]
Allowing the main class to be swapped via configuration makes it easier to extend new features without re-implementing the plugin, while maintaining flexibility for future enhancements. As you can see, most plugins allow you to swap the resource class implementation. This is because it makes our implementation more specific without needing to suggest changes to the core code. :smile:

**Comment by bezhanSalleh** [comment]
hmm... So you basically want to swap the role resource with your own implementation, is that what you are saying right?. you want the cli stuff but also away to use your own RoleResource instead. Now this distinction is very important because if it's just the question of overriding a couple methods then, that would be totally different.

**Comment by bezhanSalleh** [comment]
to override a method let's take your example of the navigation label.
1. create a resource and delete the pages and stuff or just a class in your specific panel's resource directory.
```php
//ShieldOverrideResource.php
<?php

namespace App\Filament\Resources;

use BezhanSalleh\Shield\Resources\RoleResource;

class ShieldOverrideResource extends RoleResource
{
    public static function getNavigationLabel(): string
    {
        return 'Roles & Permissions';
    }
    
    // this is to avoid duplication
    public static function shouldRegisterNavigation(): bool
    {
        return true;
    }
}
```
2. from `filament-shield.php` config disable the `should_register_navigation`. this is to avoid duplication
```php
    'shield_resource' => [
        'should_register_navigation' => false,
        ...
```   
3. in your `AppServiceProvider` or any other service provider's `boot()` method bind the your own implementation.
```php
use BezhanSalleh\Shield\Resources\RoleResource;

class AppServiceProvider extends ServiceProvider
{
   ...
   public function boot()
   {
        $this->app->bind(RoleResource::class, \App\Filament\Resources\ShieldOverrideResource::class);
        
        ...
   }
   ...
```

now you can override anything your heart desires and without re-writing the whole plugin as you put it.
hope this is what you want. let me know.

**Comment by a21ns1g4ts** [comment]
@bezhanSalleh If this works, it's very good. I didn't try it before because I thought you needed to use the Make app in your implementation, but I think if it's like this, it's much better. I'll try and let you know if it worked.

**Comment by a21ns1g4ts** [comment]
@bezhanSalleh I just tested it, and this doesn't work. That's because Filament doesn't instantiate the class internally through the injection container.

**Comment by bezhanSalleh** [comment]
> ```
> $this->app->bind(RoleResource::class, \App\Filament\Resources\ShieldOverrideResource::class);
> ```

FYI, you don't have to tag me, it's my repo so i get notified anyway. 
Also the code i give you isn't a sample it's working code.
here ... https://github.com/bezhanSalleh/shield-demo

It's a common way to override things in laravel so if it still doesn't work then you might have something somewhere faulty on your code base.

**Comment by bezhanSalleh** [comment]
> @bezhanSalleh I just tested it, and this doesn't work. That's because Filament doesn't instantiate the class internally through the injection container.

FYI, you don't have to tag me, it's my repo so i get notified anyway.
Also the code i give you isn't a sample it's working code.
here ... https://github.com/bezhanSalleh/shield-demo

It's a common way to override things in laravel so if it still doesn't work then you might have something somewhere faulty on your code base.

**Comment by a21ns1g4ts** [comment]
Ok. Sorry to bother you, but this is very important to me. I tried doing what you said, but I didn't get any results. Can I contact you through Discord? Thank you very much!

**Comment by afsakar** [comment]
Sorry for bump this conversation but i have to do same thing. Did you find any solution? @a21ns1g4ts

**Comment by a21ns1g4ts** [comment]
@afsakar  Not really sure what you meant, but in my case, I was trying to swap out the resource class implementation, and I couldn't get it to work with bind. Honestly, I don’t know how they say it’s possible ‘cause I don’t think it is. Most Filament packages have that option in the config file, but this one doesn’t seem to. Also noticed they’re not super open to contributions. Might be better to find a more open fork, or even start our own. That’s something I’m considering too.

**Pull request closed without merging**
